### ISSUE TITLE
React-Query 적용 및 리팩토링

### ISSUE THREAD

**Issue by YueunKim** [pie-sfac/1-16-careMango#171]
## Todo

- [x] Modal 컴포넌트 확인 버튼 하나만 있는 경우 추가
- [x] App QueryClientProvider로 감싸기

### 회원 관리

- 회원 생성 (createMembers)
  - [x] useMutation 적용
  - [x] onChange, handleInputChange 함수 제거하고 handleChange에 통합
  - [x] 완료 버튼 활성화 조건에 약관 동의 포함

- 회원 조회 (getMembers)
  - [x] useQuery 적용
  - [x] 검색과 페이지네이션 분리

- 회원 상세 조회 (getMembersDetail)
  - [x] useQuery 적용
  - [x] activeTab에 따른 컴포넌트 렌더링 부분을 조건부 렌더링으로 수정

- 회원 정보 변경 (updateMembers)
  - [x] useQuery 적용
  - [x] useMutation 적용
  - [x] onChange, handleInputChange, numberChange 함수 제거하고 handleChange에 통합

### 상담 일정 관리

- 상담 일정 생성 (createCounseling)
  - [x] useMutation 적용
  - [x] 불필요한 recoil 사용 취소 (timeList만 recoil적용)
 
- 상담 일정 조회 (schedulApi)
  - [x] useQuery 적용

- 상담 상세 일정 조회 및 취소 (getCounselingDetail)
  - [x] useQuery 적용
  - [x] useMutation 적용
  - [x] 불필요한 useRecoilState 제거
  - [x] 문자열 파싱 함수 생성하여 코드 간소화

- 상담 일정 변경 (updateCounseling)
  - [x] useQuery 적용
  - [x] useMutation 적용
  - [x] numberChange, onDateChange 함수 제거하고 handleChange에 통합

- 상담 기록 (CounselingScheduleDetail)
  - [x] useQuery 적용
  - [x] useMutation 적용
  - [x] 구조 분해 할당으로 itemData 참조
  - [x] 반복되는 버튼 스타일을 상수로 분리
