### ISSUE TITLE
일정조회-개인수업 수정 및 컴포넌트 분리

### ISSUE THREAD

**Issue by lyeejj** [pie-sfac/1-16-careMango#23]
## Todo

- [x] 일정조회-개인수업 Card 컴포넌트 분리
- [x]  Tailwind CSS 커스텀 스타일로 스타일링 수정
- [x]  typescript 타입 선언
