### ISSUE TITLE
로그인 페이지 스타일링 + 기능완성

### ISSUE THREAD

**Issue by s-ja** [pie-sfac/1-16-careMango#37]
## Todo

- [ ]  로그인 페이지 스타일링
- [ ] API 통신 기능 구현 완성
- [ ] 사용자 로그인 정보에 따른 Main page 이동 기능 구현
- [ ] 테스트
- [ ] ~~기능 개선 및 최적화~~
