### ISSUE TITLE
일정조회-개인수업 이벤트처리

### ISSUE THREAD

**Issue by lyeejj** [pie-sfac/1-16-careMango#43]
## Todo
- [x] 출결체크 이벤트 핸들링
  - [x] 출결상태에 따라 스타일링 변경
- [x] 날짜, 시간 생성함수 utils 폴더 만들어 생성
- [x] 변경 클릭시 일정변경 페이지로 이동
