### ISSUE TITLE
일정관리-상담-일정 생성/상세조회 페이지 수정

### ISSUE THREAD

**Issue by YueunKim** [pie-sfac/1-16-careMango#67]
## Todo

1. createCounseling
- [x] 입력값 업데이트 수정
- [x] 완료버튼 안눌리는 부분 오류 수정
- [x] 완료버튼 클릭시 /schedule 페이지로 이동

2. checkCounseling
- [x] 변경버튼 클릭 시 생성 페이지로 이동
