### ISSUE TITLE
센터수강권 상세 페이지 생성 및 센터수강권 조회 세부기능 추가

### ISSUE THREAD

**Issue by lyeejj** [pie-sfac/1-16-careMango#91]
## Todo

- [x] 센터/회원 기준에 따른 상세페이지
  - [x] 센터수강권 상세 페이지 생성 
    - 상세페이지에서 토글버튼(:) 추가 
    - 편집, 판매종료, 수강권 삭제 페이지 또는 모달 생성 + api 연동
    - 수강권 부여내역 버튼, 페이지 생성
  - [x] 회원에게 부여된 수강권 상세 페이지 생성
- [x] 수강권 티켓 페이지 폴더/파일명 변경 및 정리
- [x] TicketList 컴포넌트 생성하여 중복코드 최소화
